name: Build and Push Image

on:
  workflow_dispatch:
  push:
    branches:
        - master

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    # Build Docker image
    # -------------------------------------------------------
    - name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}
        repository: mxrch/ghunt
        tags: mxrch/ghunt:latest
        dockerfile: Dockerfile