name: Build and Push Image

on:
  workflow_dispatch:
  push:
    branches:
        - master

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
     -
      name: Checkout
      uses: actions/checkout@v2
     -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
     -
      name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
     -
      name: Build and push Docker images
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: mxrch/ghunt:latest
     -
      name: Update repo description
      uses: peter-evans/dockerhub-description@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        repository: mxrch/ghunt